# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-Jsgd-MPtBzMqQWBAMYVA_zcc7UgdCn
"""

import argparse
import numpy as np
from scipy import signal
import soundfile as sf
import matplotlib.pyplot as plt
import os

def plot_signals(u, h, y, fs, output_path):
    print("[*] Generating signal waveforms...")
    # Create time axes (in seconds)
    t_u = np.linspace(0, len(u) / fs, num=len(u))
    t_h = np.linspace(0, len(h) / fs, num=len(h))
    t_y = np.linspace(0, len(y) / fs, num=len(y))

    fig, axs = plt.subplots(3, 1, figsize=(10, 8))
    fig.tight_layout(pad=4.0)

    axs[0].plot(t_u, u, color='blue')
    axs[0].set_title('1. Input Signal (Dry Audio)')
    axs[0].set_ylabel('Amplitude')

    axs[1].plot(t_h, h, color='red')
    axs[1].set_title('2. Impulse Response (System Characteristic)')
    axs[1].set_ylabel('Amplitude')

    axs[2].plot(t_y, y, color='purple')
    axs[2].set_title('3. Output Signal (Convolved Audio)')
    axs[2].set_xlabel('Time (Seconds)')
    axs[2].set_ylabel('Amplitude')

    plt.savefig(output_path)
    print(f"[+] Waveform graphs saved to: {output_path}")
    plt.close()

def apply_convolution(input_audio_path, impulse_response_path, output_audio_path):
    print("[*] Processing started...\n")
    try:
        u, fs_u = sf.read(input_audio_path)
        h, fs_h = sf.read(impulse_response_path)
    except Exception as e:
        print(f"[!] Error: Could not read the files. Details: {e}")
        return

    if len(u.shape) > 1:
        u = np.mean(u, axis=1)
    if len(h.shape) > 1:
        h = np.mean(h, axis=1)

    y = signal.convolve(u, h, mode='full')
    y_normalized = y / np.max(np.abs(y))

    output_dir = os.path.dirname(output_audio_path)
    if output_dir:
         os.makedirs(output_dir, exist_ok=True)

    sf.write(output_audio_path, y_normalized, fs_u)
    print(f"\n[+] SUCCESS! Output audio saved to: {output_audio_path}")

    plot_path = os.path.join(output_dir if output_dir else ".", "waveform_comparison.png")
    plot_signals(u, h, y_normalized, fs_u, plot_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LTI Systems: Audio Convolution Simulator")
    parser.add_argument("-i", "--input", type=str, required=True, help="Path to input audio file")
    parser.add_argument("-ir", "--impulse", type=str, required=True, help="Path to impulse response file")
    parser.add_argument("-o", "--output", type=str, default="outputs/result_audio.wav", help="Path to save output audio")

    args = parser.parse_args()
    apply_convolution(args.input, args.impulse, args.output)